version: '3'
services:
  ng:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/usr/share/nginx/html/ssl
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/tmp.ng
      - ./nginx/dev.conf:/etc/nginx/conf.d/tmp.ng
    environment:
      APP_PORT: 3000
      APP_NAME: koa
    command: /bin/bash -c "envsubst '$$APP_PORT $$APP_NAME' < /etc/nginx/conf.d/tmp.ng > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
      - ./init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
  koa:
    image: node
    restart: always
    environment:
      APP_PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PWD: 123456
      DB_NAME: daily_msg
    ports:
      - 3000
    volumes:
      - ./app/:/koa/
    command:
      - /bin/sh
      - -c
      - |
        cd /koa && npm install && npm start

