version: '3'
services:
  ng:
    image: nginx
    restart: always
    ports:
      - ${NG_HTTP}:${NG_HTTP}
      - ${NG_HTTPS}:${NG_HTTPS}
    volumes:
      - ./ssl:/usr/share/nginx/html/ssl
      - ./nginx/${NG_ENV:-pro}.conf:/etc/nginx/conf.d/tmp.ng
    environment:
      APP_PORT: ${APP_PORT}
      APP_NAME: ${APP_NAME}
    command: /bin/bash -c "envsubst '$$APP_PORT $$APP_NAME' < /etc/nginx/conf.d/tmp.ng > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
      - ./init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
  koa:
    image: node
    restart: always
    environment:
      APP_PORT: ${APP_PORT}
      DB_HOST: db
      DB_PORT: ${MYSQL_PORT}
      DB_USER: root
      DB_PWD: ${MYSQL_PWD}
      DB_NAME: ${DB_NAME}
    ports:
      - ${APP_PORT}
    volumes:
      - ./app/:/koa/
    command:
      - /bin/sh
      - -c
      - |
        cd /koa && npm install && npm start

