version: '3'
services:
  ng:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./web:/usr/share/nginx/html/web
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
      - ./init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: 'test'
      MYSQL_PASS: '123456'
    ports:
      - 3306:3306
  koa:
    image: node
    restart: always
    volumes:
      - ./src/:/koa/
    command:
      - /bin/sh
      - -c
      - |
        cd /koa/ \
        && npm install -g cnpm --registry=https://registry.npm.taobao.org \
        && cnpm install -g nodemon \
        && cnpm install \
        && nodemon app.js

