version: '3'
services:
  ng:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/usr/share/nginx/html/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
      - ./init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
  koa:
    image: node
    restart: always
    environment:
      appPort: 3000
      host: db
      port: 3306
      user: root
      password: 123456
      database: daily_msg
    ports:
      - 3000:3000
    volumes:
      - ./app/:/koa/
    command:
      - /bin/sh
      - -c
      - |
        cd /koa && npm install && npm start

